server:
  port: 8002


#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.98.248.203:3306/muxin?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root123

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@47.98.248.203:1521/helowin
    username: MUXIN2
    password: muxin2


  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 密码
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


#密钥
#secretkey: 123456

swagger:
  enabled: true
  title: controller-demo
  description: "测试swagger"
  version: 4.0.0

  contact:
    name: rgas
    email: xxx@qq.com
    url: www.baidu.com

#spring.mvc:
#  #  这个mvc的配置是springboot2.6.1不支持swagger3的折衷配置，后面考虑升级Springboot版本或降级版本
#  pathmatch:
#    matching-strategy: ant_path_matcher


mybatis-plus:
#  global-config:
#    db-config:
#      id-type: assign_id
#  configuration:
#          log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

