public.cloud.service.url.rgas-adapter: 192.168.92.114:8201


test.name: lisi
test.age: 18

server.port: 7770
management:
  endpoints:
    enabled-by-default: false #关闭监控
    web:
      exposure:
        include: '*'
